### ISSUE TITLE
Plan for v0.4

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#107]
## For v0.4:

- [x] Add decorated intervals [branch `decorations`]; #112 
- [x] Add mechanism to change display options; #115 
- [x] Revise narrative docs to reflect changes in 0.4; #118 #123
- [x] NEWS.md updates; #122

**Comment by dpsanders** [comment]
We should transition to using milestones rather than these kind of global issues.

**Comment by dpsanders** [comment]
I am planning to tag 0.4 very soon. Any objections @lbenet?

**Comment by lbenet** [comment]
Sorry for the late reply: no, no objections. Go ahead!

**Comment by dpsanders** [comment]
v0.4 has been tagged and published!
