### ISSUE TITLE
Plan for v0.1

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#23]
### For v0.1:

**Required:**
- [x] Correct trig functions for points near boundaries of quadrants. RFC (and for tests): #20 
- [x] Documentation with `mkdocs`. RFC: #30 
- [x] Finish alternative roundings by changing tests to work with both roundings. RFC: #29
- [x] Incorporate functions from @jverzani [`ImplicitEquations` package] (https://github.com/jverzani/ImplicitEquations.jl/blob/master/src/intervals.jl) #32
- [x] Improve Krawczyk in 1D. @lbenet #26
- [x] Rename `findroots` -> `find_roots`. #26
- [x] Version of `find_roots` (with different name) returning midpoint and radius instead of interval #35 
- [x] Tests with higher precision e.g. for the Newton method #29
- [x] Add test coverage info and badge
- [x] Move rounding mode, precision, etc. into an `IntervalParameters` object #29
- [x] Add `set_interval_precision` that changes `big_pi` for interval trig #29
- [x] Or use `set_interval_precision` to choose between `Float64` and `BigFloat`. #29 
- [x] Example notebooks #36 

cc @lbenet 

**Rejected:**
- Make `@interval` default to `Float64`s and replace `@floatinterval` by `@biginterval`
[There are @floatinterval and @biginterval macros, but @interval is preferred, which now uses the `interval_parameters` object to determine the type of interval created]

- Add constructors for `Interval` that automatically round single arguments?
[I think this would be more confusing.]

**Comment by dpsanders** [comment]
@jverzani Would you be happy for us to incorporate the functions you wrote?

**Comment by lbenet** [comment]
Yo también trataré de avanzar en #20 y Krawczyk ;-)

**Comment by jverzani** [comment]
More than. Thanks.

On Wed, May 6, 2015 at 7:19 PM, David P. Sanders <notifications@github.com>
wrote:

> @jverzani <https://github.com/jverzani> Would you be happy for us to
> incorporate the functions you wrote?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dpsanders/ValidatedNumerics.jl/issues/23#issuecomment-99641775>
> .
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by dpsanders** [comment]
@jverzani Great, thanks!

**Comment by dpsanders** [comment]
@jverzani Would you like to make a Pull Request so that your contribution is recorded? Or shall I just go ahead and copy in those functions and add you to the list of contributors?

**Comment by jverzani** [comment]
Whatever is easier for you. I don't need anything recorded. Thanks for
asking though.

On Wed, May 6, 2015 at 8:45 PM, David P. Sanders <notifications@github.com>
wrote:

> @jverzani <https://github.com/jverzani> Would you like to make a Pull
> Request so that your contribution is recorded? Or shall I just go ahead and
> copy in those functions and add you to the list of contributors?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dpsanders/ValidatedNumerics.jl/issues/23#issuecomment-99660686>
> .
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by dpsanders** [comment]
@jverzani Feel free to send a Pull Request if you would like to; otherwise I'll include them myself once the other outstanding things are completed.

**Comment by jverzani** [comment]
Just include them, that's easiest for me. Thanks again.

On Wed, May 6, 2015 at 8:48 PM, David P. Sanders <notifications@github.com>
wrote:

> @jverzani <https://github.com/jverzani> Feel free to send a Pull Request
> if you would like to; otherwise I'll include them myself once the other
> outstanding things are completed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dpsanders/ValidatedNumerics.jl/issues/23#issuecomment-99661124>
> .
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by lbenet** [comment]
I tagged two items of the list, which are implemented by #26

**Comment by dpsanders** [comment]
Tagged 0.1. Closing!
