### ISSUE TITLE
Plan for v0.2

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#31]
#### For v0.2:
- [x] Improve test coverage
- [x] Wrap `CRlibm`. Done in https://github.com/dpsanders/CRlibm.jl
- [x] Use `CRlibm` #56
- [x] Improve conformance with IEEE 1788, using the [ITF-1788](https://github.com/oheim/ITF1788) tests. #56 #78
- [x] Use new MPFR wrappers in `CRlibm` version 0.2 to clean up the duplicated code for `sin` etc. #78
- [x] Incorporate the ITF-1788 test suite as a dependency. #78
- [x] Improve conformance with IEEE 1788 further.  #67 & #78

**Comment by dpsanders** [comment]
Apparently we are ready to release 0.2! What do you think, @lbenet?

We need to work on documentation though...

**Comment by lbenet** [comment]
I think we should improve the documentation before, both the long one, and the doc strings.

**Comment by dpsanders** [comment]
I've added these to the checklist, but it's not clear when that will be "finished"...

**Comment by dpsanders** [comment]
After offline discussion with @lbenet, it was decided to tag v0.2 now and add documentation when possible before v0.3.
