### ISSUE TITLE
Items for v0.3

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/ValidatedNumerics.jl#61]
## For v0.3:
- [x] Multi-dimensional intervals #88 
- [x] Refactoring #98 #100
- [x] Replace our home-grown automatic differentiation with [ForwardDiff.jl](https://github.com/JuliaDiff/ForwardDiff.jl) #101 
- [x] Improve narrative documentation  #104 

-----

#### Removed
-  ~~Add support for `DoubleDouble`~~ The `DoubleDouble` package does not provide correctly-rounded functions.

**Comment by lbenet** [comment]
Before v0.3, we should probably increase the tests coverage and update the documentation, both internally (API) and the user manual.

**Comment by dpsanders** [comment]
I have updated the user manual with the syntax changes and some improvements, e.g. providing a list of supported unary functions (`sin` etc.). Many of the other functions will be better documented with an automatic API documentation scheme like `Documenter.jl` (#105).

I suggest we tag version 0.3 and delay this til the next version, as we discussed offline.
